### ISSUE TITLE
Bug: 腾讯云部署 TypeError 报错

### ISSUE THREAD

**Issue by geziye** [ceajs/cea#1]
2021-07-05T03:02:15.118Z 5e775a33-8376-4416-8c9d-3cc997c4133e ✔  成功        成功加载用户 @txc

2021-07-05T03:02:15.648Z 5e775a33-8376-4416-8c9d-3cc997c4133e ✔  成功        学校 福州大学 默认签到地址：福州市闽侯县乌龙江大道2号

2021-07-05T03:02:15.648Z 5e775a33-8376-4416-8c9d-3cc997c4133e ✔  成功        学校 福州大学 已完成设定

2021-07-05T03:02:15.834Z 5e775a33-8376-4416-8c9d-3cc997c4133e (node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined

    at Object.cookieParse (/var/user/node_modules/cea-core/lib/src/utils/cookie-helper.js:15:13)

    at FetchWithCookie.<anonymous> (/var/user/node_modules/cea-core/lib/src/utils/fetch-helper.js:66:44)

    at Generator.next (<anonymous>)

    at fulfilled (/var/user/node_modules/cea-core/lib/src/utils/fetch-helper.js:5:58)

    at process._tickCallback (internal/process/next_tick.js:68:7)

2021-07-05T03:02:15.834Z 5e775a33-8376-4416-8c9d-3cc997c4133e (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

2021-07-05T03:02:15.834Z 5e775a33-8376-4416-8c9d-3cc997c4133e (node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

END RequestId: 5e775a33-8376-4416-8c9d-3cc997c4133e

Report RequestId: 5e775a33-8376-4416-8c9d-3cc997c4133e Duration:1415ms Memory:256MB MemUsage:37.418MB

**Comment by beetcb** [comment]
@geziye 云函数部署的 cea 的版本落后了(0.0.8 -> 0.3.2)，我更新一下，你只需要重新部署一遍就好了

**Comment by beetcb** [comment]
Moved to #2
