### ISSUE TITLE
腾讯云部署问题

### ISSUE THREAD

**Issue by luckycat0426** [ceajs/cea#13]
腾讯云镜像是不是要更新了,删除云函数之后按照流程重新部署了一次,发现代码还是以前的.

**Comment by beetcb** [comment]
我错了，我忘了它是写代码运行的（不是命令行） 😂，直接异步导入就可以了 @luckycat0426

**Comment by beetcb** [comment]
云函数支持的最高版本为 12.6，需要 `--experimental-modules` 标签运行，而且就算运行了，他这个 `import(path)` 函数中的 `path` 并不支持多层路径或npm包的解释

真难搞，这种方案又得放弃！
```bash
hello@vultr:~/cea# node --experimental-modules i.js
(node:47074) ExperimentalWarning: The ESM module loader is experimental.
(node:47074) UnhandledPromiseRejectionWarning: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:36:11)
    at Loader.resolve (internal/modules/esm/loader.js:94:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:240:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36)
(node:47074) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:47074) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by luckycat0426** [comment]
https://deno.com/deploy/
不知道用deno打包成可执行文件，然后云函数调用shell运行可不可行

**Comment by beetcb** [comment]
花时间用 esbuild 编译了所有纯 esm 的依赖，测试可成功部署到云开发并运行 @luckycat0426
