### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by allinu** [ceajs/cea#39]
CPU: Apple M1 
npm: 8.4.0 
nodejs: v17.4.0

<img width="1326" alt="图片" src="https://user-images.githubusercontent.com/32992109/155002673-df550fde-ff4e-4e22-af66-80e05ca343b9.png">

```
➜  ~ cea load conf.toml && cea sign
✔  成功        成功加载用户 @liona
✔  成功        学校 XXXXX 已完成设定，接入方式为 CLOUD
✔  成功        登录成功 @liona
✔  成功        已成功获取并缓存 COOKIE @liona
file:///opt/homebrew/lib/node_modules/cea/node_modules/@ceajs/check-in-helper/lib/src/index.js:171
            const signedSelectedItemValue = curSignedExtraField.extraFieldItems.find((e) => e.isSelected === true).value;
                                                                                                                  ^

TypeError: Cannot read properties of undefined (reading 'value')
    at file:///opt/homebrew/lib/node_modules/cea/node_modules/@ceajs/check-in-helper/lib/src/index.js:171:115
    at Array.map (<anonymous>)
    at Function.fillExtra (file:///opt/homebrew/lib/node_modules/cea/node_modules/@ceajs/check-in-helper/lib/src/index.js:167:27)
    at CheckIn.signWithForm (file:///opt/homebrew/lib/node_modules/cea/node_modules/@ceajs/check-in-helper/lib/src/index.js:66:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///opt/homebrew/lib/node_modules/cea/node_modules/@ceajs/check-in-helper/lib/src/index.js:215:36
    at async Promise.all (index 0)
    at async Function.signIn (file:///opt/homebrew/lib/node_modules/cea/node_modules/@ceajs/check-in-helper/lib/src/index.js:208:9)
    at async checkIn (file:///opt/homebrew/lib/node_modules/cea/node_modules/@ceajs/sign-plugin/lib/src/index.js:7:22)
    at async file:///opt/homebrew/lib/node_modules/cea/lib/src/cli.js:42:13

Node.js v17.4.0
```

<img width="868" alt="图片" src="https://user-images.githubusercontent.com/32992109/155002885-38adcf86-ec0f-4996-a932-6c5d1972a7c3.png">

EMMMM 手机端签到完毕后再次测试，没有报错了，不知道问题出在哪里

<img width="707" alt="图片" src="https://user-images.githubusercontent.com/32992109/155003187-f5d78439-ea42-4f70-985f-cbc52ddc7bf9.png">

前几天是登陆之前就报错（没有及时保留报错信息），登录不上，现在能登录上了，好像是在获取之前的签到信息和提交的过程中出错了，技术小白，不知道提供的这写能不能找到问题

CEA 版本未知
但是我是在执行完下面的命令后运行的，应该是最新的发行版吧

<img width="1438" alt="图片" src="https://user-images.githubusercontent.com/32992109/155003707-91ceb382-db31-4107-8b52-a062e0466028.png">

**Comment by allinu** [comment]
如果需要其他信息，我也方便提供

**Comment by beetcb** [comment]
这个报错是尝试在历史签到中找已经选择的选项，没找到
1. 2021 12 月份是否有成功签到的历史数据呢 ？
2. 请问你们签到的表单是选择之外的形式吗（比如文字输入）？
@allinu

**Comment by allinu** [comment]
@beetcb 

1. 我之前一直使用这个配置，都可一签到成功，但是最近有点不行了，**我今晚再试试这个月，可能表单数据变化了**
2. 不是，我们的表单就是选择表单，没有之外的形式，都是选择题

如果不是代码的问题，我在自己研究研究

**Comment by beetcb** [comment]
要不尝试一下最新的年月份默认配置？

![image](https://user-images.githubusercontent.com/63141491/155072225-e56f6298-b8c7-4454-a836-f8ad2cc3b8f2.png)

**Comment by allinu** [comment]
好的，今晚就尝试尝试 ♥️

**Comment by allinu** [comment]
```shell
➜  ~ cea load conf.toml && cea sign
✔  成功        成功加载用户 @liona
✔  成功        学校 xxxxxx 已完成设定，接入方式为 CLOUD
✔  成功        登录成功 @liona
✔  成功        已成功获取并缓存 COOKIE @liona
┌─────────┬─────────────────────────────────────────────────────────────┐
│ (index) │                          签到结果                           │
├─────────┼─────────────────────────────────────────────────────────────┤
│  liona  │ '无法获取历史签到数据作为模板，请检查 signedDataMonth 配置' │
└─────────┴─────────────────────────────────────────────────────────────┘
➜  ~ vim conf.toml                                                                              
➜  ~ npm install -g npm            

changed 22 packages in 1s

11 packages are looking for funding
  run `npm fund` for details
➜  ~ npm install -g cea
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 439 packages in 13s
➜  ~ cea load conf.toml && cea sign
✔  成功        成功加载用户 @liona
✔  成功        学校 xxxxxx 已完成设定，接入方式为 CLOUD
✔  成功        登录成功 @liona
✔  成功        已成功获取并缓存 COOKIE @liona
┌─────────┬──────────────────┐
│ (index) │     签到结果     │
├─────────┼──────────────────┤
│  liona  │ '当前无签到任务' │
└─────────┴──────────────────┘
➜  ~ cea load conf.toml && cea sign
✔  成功        成功加载用户 @liona
✔  成功        学校 xxxxxx 已完成设定，接入方式为 CLOUD
✔  成功        登录成功 @liona
✔  成功        已成功获取并缓存 COOKIE @liona
┌─────────┬──────────────────┐
│ (index) │     签到结果     │
├─────────┼──────────────────┤
│  liona  │ '当前无签到任务' │
└─────────┴──────────────────┘
➜  ~ vim conf.toml                 
➜  ~ cea load conf.toml && cea sign
✔  成功        成功加载用户 @liona
✔  成功        学校 xxxxxx 已完成设定，接入方式为 CLOUD
✔  成功        登录成功 @liona
✔  成功        已成功获取并缓存 COOKIE @liona
┌─────────┬──────────────────┐
│ (index) │     签到结果     │
├─────────┼──────────────────┤
│  liona  │  '当前无签到任务'  │
└─────────┴──────────────────┘
➜  ~ 

```

匪夷所思，第一次说读取不到，之后说没有签到任务
但是我看了手机，并未签到成功，还是未签到的状态

我删除了配置中的签到时间，使用的默认时间

**Comment by beetcb** [comment]
请确保移除 NPM 缓存，安装 cea 的最新版 @allinu 

```
npm cache clean --force
npm i -g cea

npm list -g
# 确保版本是v2.5.6+
```

**Comment by allinu** [comment]
好的，我执行完毕了，今晚试试

<img width="730" alt="图片" src="https://user-images.githubusercontent.com/32992109/155259106-a9c24971-5a53-4e75-90b4-f5e1b3fd9a16.png">

**Comment by allinu** [comment]
<img width="730" alt="图片" src="https://user-images.githubusercontent.com/32992109/155368515-f13ffdf6-3b60-4d58-95ab-eac0a2fa153b.png">


看来是缓存的问题，我之前安装没有清除缓存，打扰了 😘
