### ISSUE TITLE
查寝功能报错

### ISSUE THREAD

**Issue by Mosimita** [ceajs/cea#40]
OS: Almalinux 8.5
Version: Node.js v16.8.0 cea@2.5.6
貌似只有查寝不可用
签到功能是正常的
不过去年查寝也还能用的（
以下是log
```
[root@server cea]# cea attendance
✔  成功        登录成功 @test
✔  成功        已成功获取并缓存 COOKIE @test
file:///usr/local/lib/node_modules/cea/node_modules/@ceajs/check-in-helper/lib/src/index.js:184
        const isSignedTemplateMatch = signedExtraField.every((ele, idx) => { var _a; return ele.title === ((_a = extraField[idx]) === null || _a === void 0 ? void 0 : _a.title); });
                                                       ^

TypeError: Cannot read property 'every' of undefined
    at Function.fillExtra (file:///usr/local/lib/node_modules/cea/node_modules/@ceajs/check-in-helper/lib/src/index.js:184:56)
    at CheckIn.signWithForm (file:///usr/local/lib/node_modules/cea/node_modules/@ceajs/check-in-helper/lib/src/index.js:67:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///usr/local/lib/node_modules/cea/node_modules/@ceajs/check-in-helper/lib/src/index.js:234:36
    at async Promise.all (index 0)
    at async Function.signIn (file:///usr/local/lib/node_modules/cea/node_modules/@ceajs/check-in-helper/lib/src/index.js:227:9)
    at async attendanceCheckIn (file:///usr/local/lib/node_modules/cea/node_modules/@ceajs/attendance-plugin/lib/src/index.js:7:22)
    at async file:///usr/local/lib/node_modules/cea/lib/src/cli.js:46:13
```

**Comment by Mosimita** [comment]
试了一下降级cea
每次执行均移除cea后移除npm缓存再安装
2.5.6版本抛出同样错误
2.5.5版本检测不到查寝
```
[root@server cea]# cea attendance
✔  成功        尝试使用缓存中的 COOKIE @test
┌─────────┬──────────────────┐
│ (index) │     签到结果     │
├─────────┼──────────────────┤
│  test   │ '当前无签到任务' │
└─────────┴──────────────────┘
```
2.5.4版本能够查寝成功
```
[root@server cea]# cea sign
✔  成功        尝试使用缓存中的 COOKIE @test
┌─────────┬───────────┬───────────────────────────────────────┐
│ (index) │ 签到结果  │               签到地址                │
├─────────┼───────────┼───────────────────────────────────────┤
│  test   │ 'SUCCESS' │ '****************' │
└─────────┴───────────┴───────────────────────────────────────┘
```

**Comment by beetcb** [comment]
请问有尝试自定义模板数据月份吗？

https://github.com/ceajs/cea/issues/39#issuecomment-1047453475

@Mosimita

**Comment by beetcb** [comment]
https://github.com/ceajs/cea/commit/e738ebb1bf4ec39abe0e99a7c7e73939e7e1968a 更新了签到逻辑，没有考虑到查寝 :) 

我的锅 @Mosimita

**Comment by Mosimita** [comment]
我就说，绝了，我还以为环境有问题，还给我npm都重装了

**Comment by beetcb** [comment]
紧急更了一版，应该解决了 @Mosimita
